# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nikitaterekhov/CLionProjects/e-chess

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nikitaterekhov/CLionProjects/e-chess

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cpack --config ./CPackSourceConfig.cmake /Users/nikitaterekhov/CLionProjects/e-chess/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikitaterekhov/CLionProjects/e-chess/CMakeFiles /Users/nikitaterekhov/CLionProjects/e-chess/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nikitaterekhov/CLionProjects/e-chess/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named e-chess

# Build rule for target.
e-chess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 e-chess
.PHONY : e-chess

# fast build rule for target.
e-chess/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/build
.PHONY : e-chess/fast

CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

src/controller/GameController.o: src/controller/GameController.cpp.o

.PHONY : src/controller/GameController.o

# target to build an object file
src/controller/GameController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/controller/GameController.cpp.o
.PHONY : src/controller/GameController.cpp.o

src/controller/GameController.i: src/controller/GameController.cpp.i

.PHONY : src/controller/GameController.i

# target to preprocess a source file
src/controller/GameController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/controller/GameController.cpp.i
.PHONY : src/controller/GameController.cpp.i

src/controller/GameController.s: src/controller/GameController.cpp.s

.PHONY : src/controller/GameController.s

# target to generate assembly for a file
src/controller/GameController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/controller/GameController.cpp.s
.PHONY : src/controller/GameController.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/Bishop.o: src/model/Bishop.cpp.o

.PHONY : src/model/Bishop.o

# target to build an object file
src/model/Bishop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Bishop.cpp.o
.PHONY : src/model/Bishop.cpp.o

src/model/Bishop.i: src/model/Bishop.cpp.i

.PHONY : src/model/Bishop.i

# target to preprocess a source file
src/model/Bishop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Bishop.cpp.i
.PHONY : src/model/Bishop.cpp.i

src/model/Bishop.s: src/model/Bishop.cpp.s

.PHONY : src/model/Bishop.s

# target to generate assembly for a file
src/model/Bishop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Bishop.cpp.s
.PHONY : src/model/Bishop.cpp.s

src/model/Chessboard.o: src/model/Chessboard.cpp.o

.PHONY : src/model/Chessboard.o

# target to build an object file
src/model/Chessboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Chessboard.cpp.o
.PHONY : src/model/Chessboard.cpp.o

src/model/Chessboard.i: src/model/Chessboard.cpp.i

.PHONY : src/model/Chessboard.i

# target to preprocess a source file
src/model/Chessboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Chessboard.cpp.i
.PHONY : src/model/Chessboard.cpp.i

src/model/Chessboard.s: src/model/Chessboard.cpp.s

.PHONY : src/model/Chessboard.s

# target to generate assembly for a file
src/model/Chessboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Chessboard.cpp.s
.PHONY : src/model/Chessboard.cpp.s

src/model/King.o: src/model/King.cpp.o

.PHONY : src/model/King.o

# target to build an object file
src/model/King.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/King.cpp.o
.PHONY : src/model/King.cpp.o

src/model/King.i: src/model/King.cpp.i

.PHONY : src/model/King.i

# target to preprocess a source file
src/model/King.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/King.cpp.i
.PHONY : src/model/King.cpp.i

src/model/King.s: src/model/King.cpp.s

.PHONY : src/model/King.s

# target to generate assembly for a file
src/model/King.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/King.cpp.s
.PHONY : src/model/King.cpp.s

src/model/Knight.o: src/model/Knight.cpp.o

.PHONY : src/model/Knight.o

# target to build an object file
src/model/Knight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Knight.cpp.o
.PHONY : src/model/Knight.cpp.o

src/model/Knight.i: src/model/Knight.cpp.i

.PHONY : src/model/Knight.i

# target to preprocess a source file
src/model/Knight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Knight.cpp.i
.PHONY : src/model/Knight.cpp.i

src/model/Knight.s: src/model/Knight.cpp.s

.PHONY : src/model/Knight.s

# target to generate assembly for a file
src/model/Knight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Knight.cpp.s
.PHONY : src/model/Knight.cpp.s

src/model/Pawn.o: src/model/Pawn.cpp.o

.PHONY : src/model/Pawn.o

# target to build an object file
src/model/Pawn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Pawn.cpp.o
.PHONY : src/model/Pawn.cpp.o

src/model/Pawn.i: src/model/Pawn.cpp.i

.PHONY : src/model/Pawn.i

# target to preprocess a source file
src/model/Pawn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Pawn.cpp.i
.PHONY : src/model/Pawn.cpp.i

src/model/Pawn.s: src/model/Pawn.cpp.s

.PHONY : src/model/Pawn.s

# target to generate assembly for a file
src/model/Pawn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Pawn.cpp.s
.PHONY : src/model/Pawn.cpp.s

src/model/Piece.o: src/model/Piece.cpp.o

.PHONY : src/model/Piece.o

# target to build an object file
src/model/Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Piece.cpp.o
.PHONY : src/model/Piece.cpp.o

src/model/Piece.i: src/model/Piece.cpp.i

.PHONY : src/model/Piece.i

# target to preprocess a source file
src/model/Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Piece.cpp.i
.PHONY : src/model/Piece.cpp.i

src/model/Piece.s: src/model/Piece.cpp.s

.PHONY : src/model/Piece.s

# target to generate assembly for a file
src/model/Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Piece.cpp.s
.PHONY : src/model/Piece.cpp.s

src/model/Queen.o: src/model/Queen.cpp.o

.PHONY : src/model/Queen.o

# target to build an object file
src/model/Queen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Queen.cpp.o
.PHONY : src/model/Queen.cpp.o

src/model/Queen.i: src/model/Queen.cpp.i

.PHONY : src/model/Queen.i

# target to preprocess a source file
src/model/Queen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Queen.cpp.i
.PHONY : src/model/Queen.cpp.i

src/model/Queen.s: src/model/Queen.cpp.s

.PHONY : src/model/Queen.s

# target to generate assembly for a file
src/model/Queen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Queen.cpp.s
.PHONY : src/model/Queen.cpp.s

src/model/Tower.o: src/model/Tower.cpp.o

.PHONY : src/model/Tower.o

# target to build an object file
src/model/Tower.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Tower.cpp.o
.PHONY : src/model/Tower.cpp.o

src/model/Tower.i: src/model/Tower.cpp.i

.PHONY : src/model/Tower.i

# target to preprocess a source file
src/model/Tower.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Tower.cpp.i
.PHONY : src/model/Tower.cpp.i

src/model/Tower.s: src/model/Tower.cpp.s

.PHONY : src/model/Tower.s

# target to generate assembly for a file
src/model/Tower.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/model/Tower.cpp.s
.PHONY : src/model/Tower.cpp.s

src/view/Button.o: src/view/Button.cpp.o

.PHONY : src/view/Button.o

# target to build an object file
src/view/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Button.cpp.o
.PHONY : src/view/Button.cpp.o

src/view/Button.i: src/view/Button.cpp.i

.PHONY : src/view/Button.i

# target to preprocess a source file
src/view/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Button.cpp.i
.PHONY : src/view/Button.cpp.i

src/view/Button.s: src/view/Button.cpp.s

.PHONY : src/view/Button.s

# target to generate assembly for a file
src/view/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Button.cpp.s
.PHONY : src/view/Button.cpp.s

src/view/ClickableElement.o: src/view/ClickableElement.cpp.o

.PHONY : src/view/ClickableElement.o

# target to build an object file
src/view/ClickableElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/ClickableElement.cpp.o
.PHONY : src/view/ClickableElement.cpp.o

src/view/ClickableElement.i: src/view/ClickableElement.cpp.i

.PHONY : src/view/ClickableElement.i

# target to preprocess a source file
src/view/ClickableElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/ClickableElement.cpp.i
.PHONY : src/view/ClickableElement.cpp.i

src/view/ClickableElement.s: src/view/ClickableElement.cpp.s

.PHONY : src/view/ClickableElement.s

# target to generate assembly for a file
src/view/ClickableElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/ClickableElement.cpp.s
.PHONY : src/view/ClickableElement.cpp.s

src/view/GraphicElement.o: src/view/GraphicElement.cpp.o

.PHONY : src/view/GraphicElement.o

# target to build an object file
src/view/GraphicElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/GraphicElement.cpp.o
.PHONY : src/view/GraphicElement.cpp.o

src/view/GraphicElement.i: src/view/GraphicElement.cpp.i

.PHONY : src/view/GraphicElement.i

# target to preprocess a source file
src/view/GraphicElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/GraphicElement.cpp.i
.PHONY : src/view/GraphicElement.cpp.i

src/view/GraphicElement.s: src/view/GraphicElement.cpp.s

.PHONY : src/view/GraphicElement.s

# target to generate assembly for a file
src/view/GraphicElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/GraphicElement.cpp.s
.PHONY : src/view/GraphicElement.cpp.s

src/view/Point2I.o: src/view/Point2I.cpp.o

.PHONY : src/view/Point2I.o

# target to build an object file
src/view/Point2I.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Point2I.cpp.o
.PHONY : src/view/Point2I.cpp.o

src/view/Point2I.i: src/view/Point2I.cpp.i

.PHONY : src/view/Point2I.i

# target to preprocess a source file
src/view/Point2I.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Point2I.cpp.i
.PHONY : src/view/Point2I.cpp.i

src/view/Point2I.s: src/view/Point2I.cpp.s

.PHONY : src/view/Point2I.s

# target to generate assembly for a file
src/view/Point2I.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/Point2I.cpp.s
.PHONY : src/view/Point2I.cpp.s

src/view/View.o: src/view/View.cpp.o

.PHONY : src/view/View.o

# target to build an object file
src/view/View.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/View.cpp.o
.PHONY : src/view/View.cpp.o

src/view/View.i: src/view/View.cpp.i

.PHONY : src/view/View.i

# target to preprocess a source file
src/view/View.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/View.cpp.i
.PHONY : src/view/View.cpp.i

src/view/View.s: src/view/View.cpp.s

.PHONY : src/view/View.s

# target to generate assembly for a file
src/view/View.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/e-chess.dir/build.make CMakeFiles/e-chess.dir/src/view/View.cpp.s
.PHONY : src/view/View.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... e-chess"
	@echo "... CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.17.3/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... src/controller/GameController.o"
	@echo "... src/controller/GameController.i"
	@echo "... src/controller/GameController.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model/Bishop.o"
	@echo "... src/model/Bishop.i"
	@echo "... src/model/Bishop.s"
	@echo "... src/model/Chessboard.o"
	@echo "... src/model/Chessboard.i"
	@echo "... src/model/Chessboard.s"
	@echo "... src/model/King.o"
	@echo "... src/model/King.i"
	@echo "... src/model/King.s"
	@echo "... src/model/Knight.o"
	@echo "... src/model/Knight.i"
	@echo "... src/model/Knight.s"
	@echo "... src/model/Pawn.o"
	@echo "... src/model/Pawn.i"
	@echo "... src/model/Pawn.s"
	@echo "... src/model/Piece.o"
	@echo "... src/model/Piece.i"
	@echo "... src/model/Piece.s"
	@echo "... src/model/Queen.o"
	@echo "... src/model/Queen.i"
	@echo "... src/model/Queen.s"
	@echo "... src/model/Tower.o"
	@echo "... src/model/Tower.i"
	@echo "... src/model/Tower.s"
	@echo "... src/view/Button.o"
	@echo "... src/view/Button.i"
	@echo "... src/view/Button.s"
	@echo "... src/view/ClickableElement.o"
	@echo "... src/view/ClickableElement.i"
	@echo "... src/view/ClickableElement.s"
	@echo "... src/view/GraphicElement.o"
	@echo "... src/view/GraphicElement.i"
	@echo "... src/view/GraphicElement.s"
	@echo "... src/view/Point2I.o"
	@echo "... src/view/Point2I.i"
	@echo "... src/view/Point2I.s"
	@echo "... src/view/View.o"
	@echo "... src/view/View.i"
	@echo "... src/view/View.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

